# Generated by Django 4.0.4 on 2022-06-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dass_app', '0002_choice_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_value',
            field=models.IntegerField(default=0),
        ),
    ]
