# Generated by Django 4.0.4 on 2022-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dass_app', '0003_choice_choice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
